 function mmLoadMenus(){  if (window.mm_menu_AboutUs) return;
 window.mm_menu_AboutUs = new Menu("root",250,28,"Arial, Helvetica, sans-serif",11,"#3B3B3B","#FFFFFF","#F0F0F0","#4788E6","left","middle",3,0,400,-5,7,true,true,true,0,true,false);
 mm_menu_AboutUs.addMenuItem("<img border='0' src='http://www.sionmarketing.com/images/icon_dulich.gif'/>&nbsp;THÔNG TIN VỀ CÔNG TY","window.location = 'http://www.sionmarketing.com/gioi-thieu/thong-tin-ve-cong-ty/i8.html'");
 mm_menu_AboutUs.addMenuItem("<img border='0' src='http://www.sionmarketing.com/images/icon_dulich.gif'/>&nbsp;Công ty đối tác 1","window.location = 'http://www.sionmarketing.com/gioi-thieu/cong-ty-doi-tac-1/i166.html'");
 mm_menu_AboutUs.addMenuItem("<img border='0' src='http://www.sionmarketing.com/images/icon_dulich.gif'/>&nbsp;THÔNG TIN NGƯỜI SÁNG LẬP","window.location = 'http://www.sionmarketing.com/gioi-thieu/thong-tin-nguoi-sang-lap/i6.html'");
 mm_menu_AboutUs.addMenuItem("<img border='0' src='http://www.sionmarketing.com/images/icon_dulich.gif'/>&nbsp;Công ty đối tác 2","window.location = 'http://www.sionmarketing.com/gioi-thieu/cong-ty-doi-tac-2/i167.html'");
 mm_menu_AboutUs.addMenuItem("<img border='0' src='http://www.sionmarketing.com/images/icon_dulich.gif'/>&nbsp;Thành tích và Khen thưởng","window.location = 'http://www.sionmarketing.com/gioi-thieu/thanh-tich-va-khen-thuong.html'");
 mm_menu_AboutUs.hideOnMouseOut=true;
 mm_menu_AboutUs.bgColor='#ffffff';
 mm_menu_AboutUs.menuBorder=1;
 mm_menu_AboutUs.menuLiteBgColor='#ffffff';
 mm_menu_AboutUs.menuBorderBgColor='#e8b343';
 if (window.mm_menu_Products) return;
  window.mm_menu_Products = new Menu("root",250,28,"Arial, Helvetica, sans-serif",11,"#3B3B3B","#FFFFFF","#F0F0F0","#4788E6","left","middle",3,0,400,-5,7,true,true,true,0,true,false);
 mm_menu_Products.hideOnMouseOut=true;
 mm_menu_Products.bgColor='#ffffff';
 mm_menu_Products.menuBorder=1;
 mm_menu_AboutUs.menuLiteBgColor='#ffffff';
 mm_menu_AboutUs.menuBorderBgColor='#e8b343';
 if (window.mm_menu_CoDong) return;
  window.mm_menu_CoDong = new Menu("root",250,28,"Arial, Helvetica, sans-serif",11,"#3B3B3B","#FFFFFF","#F0F0F0","#4788E6","left","middle",3,0,400,-5,7,true,true,true,0,true,false);
 mm_menu_CoDong.hideOnMouseOut=true;
 mm_menu_CoDong.bgColor='#ffffff';
 mm_menu_CoDong.menuBorder=1;
 mm_menu_CoDong.menuLiteBgColor='#ffffff';
 mm_menu_CoDong.menuBorderBgColor='#e8b343';
 if (window.mm_menu_ThuVien) return;
  window.mm_menu_ThuVien = new Menu("root",200,28,"Arial, Helvetica, sans-serif",11,"#3B3B3B","#FFFFFF","#F0F0F0","#4788E6","left","middle",3,0,400,-5,7,true,true,true,0,true,false);
 mm_menu_ThuVien.addMenuItem("<img border='0' src='http://www.sionmarketing.com/images/icon_dulich.gif'/>&nbsp;Hình ảnh","window.location = 'http://www.sionmarketing.com/library/album.html'");
 mm_menu_ThuVien.addMenuItem("<img border='0' src='http://www.sionmarketing.com/images/icon_dulich.gif'/>&nbsp;Văn bản","window.location = 'http://www.sionmarketing.com/thu-vien/van-ban.html'");
 mm_menu_ThuVien.hideOnMouseOut=true;
 mm_menu_ThuVien.bgColor='#ffffff';
 mm_menu_ThuVien.menuBorder=1;
 mm_menu_ThuVien.menuLiteBgColor='#ffffff';
 mm_menu_ThuVien.menuBorderBgColor='#e8b343';
 if (window.mm_menu_XayLapCT) return;
  window.mm_menu_XayLapCT = new Menu("root",250,28,"Arial, Helvetica, sans-serif",11,"#3B3B3B","#FFFFFF","#F0F0F0","#4788E6","left","middle",3,0,400,-5,7,true,true,true,0,true,false);
 mm_menu_XayLapCT.hideOnMouseOut=true;
 mm_menu_XayLapCT.bgColor='#ffffff';
 mm_menu_XayLapCT.menuBorder=1;
 mm_menu_XayLapCT.menuLiteBgColor='#ffffff';
 mm_menu_XayLapCT.menuBorderBgColor='#e8b343';
 if (window.mm_menu_DauTuDA) return;
  window.mm_menu_DauTuDA = new Menu("root",250,28,"Arial, Helvetica, sans-serif",11,"#3B3B3B","#FFFFFF","#F0F0F0","#4788E6","left","middle",3,0,400,-5,7,true,true,true,0,true,false);
 mm_menu_DauTuDA.addMenuItem("<img border='0' src='http://www.sionmarketing.com/images/icon_dulich.gif'/>&nbsp;Các dự án khác","window.location = 'http://www.sionmarketing.com/linh-vuc-hoat-dong/dau-tu-du-an/cac-du-an-khac.html'");
 mm_menu_DauTuDA.hideOnMouseOut=true;
 mm_menu_DauTuDA.bgColor='#ffffff';
 mm_menu_DauTuDA.menuBorder=1;
 mm_menu_DauTuDA.menuLiteBgColor='#ffffff';
 mm_menu_DauTuDA.menuBorderBgColor='#e8b343';
 if (window.mm_menu_SXCuaNhua) return;
  window.mm_menu_SXCuaNhua = new Menu("root",250,28,"Arial, Helvetica, sans-serif",11,"#3B3B3B","#FFFFFF","#F0F0F0","#4788E6","left","middle",3,0,400,-5,7,true,true,true,0,true,false);
 mm_menu_SXCuaNhua.hideOnMouseOut=true;
 mm_menu_SXCuaNhua.bgColor='#ffffff';
 mm_menu_SXCuaNhua.menuBorder=1;
 mm_menu_SXCuaNhua.menuLiteBgColor='#ffffff';
 mm_menu_SXCuaNhua.menuBorderBgColor='#e8b343';
 if (window.mm_menu_DonViTV) return;
  window.mm_menu_DonViTV = new Menu("root",250,28,"Arial, Helvetica, sans-serif",11,"#3B3B3B","#FFFFFF","#F0F0F0","#4788E6","left","middle",3,0,400,-5,7,true,true,true,0,true,false);
 mm_menu_DonViTV.addMenuItem("<img border='0' src='http://www.sionmarketing.com/images/icon_dulich.gif'/>&nbsp;Các đội thi công","window.location = 'http://www.sionmarketing.com/don-vi-thanh-vien/cac-doi-thi-cong.html'");
 mm_menu_DonViTV.hideOnMouseOut=true;
 mm_menu_DonViTV.bgColor='#ffffff';
 mm_menu_DonViTV.menuBorder=1;
 mm_menu_DonViTV.menuLiteBgColor='#ffffff';
 mm_menu_DonViTV.menuBorderBgColor='#e8b343';
 mm_menu_DonViTV.writeMenus(); }